name: ChrisGSchulz
favicon: null
layout_spectrum: 0.7044488009996712
typography_spectrum: 0.28096058615483344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.18001482565887272
  lightness: 0.3633384797722101
  saturation: 0.12494764453731477
  rhythmicContrast: 0.11101666744798422
purpose: []
